name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Tests
        run: |
          docker build -t myapp .
          docker run -d -p 3000:3000 myapp
          deploy:
            runs-on: ubuntu-latest
            needs: build
        
            steps:
              - name: Deploy to Server
                uses: appleboy/ssh-action@master
                with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                    docker pull mydockerhubusername/myapp:latest
                    docker stop myapp || true
                    docker rm myapp || true
                    docker run -d -p 80:3000 --name myapp mydockerhubusername/myapp:latest
        